name: jimmy

services:
  knots:
    image: 1maa/bitcoin:v27.1.knots20240801
    command: -regtest -listenonion=0
    healthcheck:
      test: netstat -ltn | grep 18443 > /dev/null
      start_interval: 125ms
      start_period: 500ms
    ports:
      - "127.0.0.1:18444:18444"
    restart: on-failure
    volumes:
      - knots_data:/home/bitcoin/.bitcoin

volumes:
  knots_data:
